### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by zingale** [Open-Astrophysics-Bookshelf/star_formation_notes#1]
Hi Mark, these notes look great!

Regarding the PDF, I'm wondering if it is better to generate the PDF automatically instead of keeping it in the git repo (since it's kinda hard to do version control on a PDF).

I'd be happy to setup a cron job on a server to build the PDF nightly that we can link to (this is what I do with the Comp Hydro notes)

**Comment by markkrumholz** [comment]
> On May 31, 2015, at 10:15 AM, Michael Zingale <notifications@github.com> wrote:
> 
> Hi Mark, these notes look great!
> 
> Regarding the PDF, I'm wondering if it is better to generate the PDF automatically instead of keeping it in the git repo (since it's kinda hard to do version control on a PDF).
> 
> I'd be happy to setup a cron job on a server to build the PDF nightly that we can link to (this is what I do with the Comp Hydro notes)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Open-Astrophysics-Bookshelf/star_formation_notes/issues/1>.
> 

Hi Mike,

No problem. When I do my next check in, I’ll remove the compiled PDF from the repo. Please do set up the cron job.

--
Mark Krumholz

**Comment by zingale** [comment]
ok, that should be setup now, and I included a link to the nightly build on the project webpage

**Comment by markkrumholz** [comment]
> On Jun 4, 2015, at 10:47 AM, Michael Zingale <notifications@github.com> wrote:
> 
> ok, that should be setup now, and I included a link to the nightly build on the project webpage
> 

Great, thanks. I’m about to be on a long plane flight, which is ideal for editing the ebook, so I’ll probably get the next chapter checked in and remove the PDF some time over the weekend.

--
Mark Krumholz

**Comment by markkrumholz** [comment]
Hi Mike,

Just wanted to let you know that the star formation book is finally all in place. Thanks for setting up the auto-build.

> On Jun 4, 2015, at 10:47 AM, Michael Zingale <notifications@github.com> wrote:
> 
> ok, that should be setup now, and I included a link to the nightly build on the project webpage
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Open-Astrophysics-Bookshelf/star_formation_notes/issues/1#issuecomment-108989559>.
> 

--
Mark Krumholz
