### ISSUE TITLE
Radiation temperature at dust destruction radius

### ISSUE THREAD

**Issue by keflavich** [Open-Astrophysics-Bookshelf/star_formation_notes#16]
The peak wavelength given for the radiation just inside the dust destruction front is ~440 nm, but that corresponds to a ~6500 K blackbody, not the ~4300 K blackbody we've been using.

https://github.com/Open-Astrophysics-Bookshelf/star_formation_notes/blob/fc6dac3a31fecec319fe129a72eeb73b1b483de6/chapters/chapter16.tex#L209-L215

I'd suggest changing the peak wavelength to 675 nm.

The dust opacity at that wavelength is closer to 3000 cm^2/g reading off of Draine+2021 Fig 2 (675 nm = 1.5 um^-1).

It might also help to use the formal Wien's Displacement law peak (lambda_peak = 2900 micron K / T_BB) instead of the approximation used in the quoted equation.  The quoted equation (lambda = hc/4 kB T) might be more appropriate for the Planck mean opacity, but it is not the peak.

These are all really minor items - the logic in the following paragraph shows that the physical behavior is insensitive to the specific wavelength adopted - but I stumbled on this when showing it to students because I have in my mind that the sun peaks at "green", i.e., ~5000 angstroms, and the sun is hotter than our 4300 K protostar, so it should be at a shorter wavelength.

**Comment by markkrumholz** [comment]
OK, fair point. Did you want to submit a PR on this, or would you prefer that I make the change?
